### PR TITLE
Retry on Different Node

### LINKED ISSUE #49: RPC Retry on Different Node
Add a soft "migration" of tasks, we can do this by retrying failed requests on different nodes (from the list of connected nodes)

### PR DESCRIPTION
**Pull request by JackyChiu**
closes #49 
blocked on #60 

# What

This PR allows for 2 features. 
1. Mesh networks by setting max connection = 0
2. Retries on different nodes

# How

1. Mesh network is created by connecting to all service nodes
2. The retries ask for a new connection when retrying a request that errored out. It does not guarantee that a new node will be used. I personally don't think it's worth the effort to guarantee this.

### CODE REVIEW

File: cluster/rpc_test.go [hunk 1]
```diff
@@ -251,6 +424,57 @@ func TestConnectionBalancer_roundRobinSelect(t *testing.T) {
...
+
+	require.Equal(t, []Node{node, node2}, c.getSelectedNodes())
+
+	node3, close := testRPCServer(t)
+	defer close()
+	node4, close := testRPCServer(t)
+	defer close()
+
+	go func() {
+		mock.nodeChan <- []Node{node, node2, node3}
```
Comment (bkzhang) [inline cluster/rpc_test.go]: Is there a test if MaxConnections isn't 0? To see what would happen with this during `getSelectedNodes`

File: cluster/rpc.go [hunk 2]
```diff
@@ -25,16 +25,21 @@ type ConnConfig struct {
...
+	// Retries is the number of times a request is attempted to get a success. The
+	// retires are possibliy done on different nodes.
+	Retries int
 }
 
 var DefaultConnConfig = &ConnConfig{
 	MaxConnections:     3,
 	InitialNodeTimeout: 5 * time.Second,
 	DebounceTime:       3 * time.Second,
+	Retries:            1,
```
[the remark this answers is not in the document]
Comment (JackyChiu) [reply cluster/rpc.go]: Sure!

File: cluster/rpc_test.go (hunk 1 above)
Comment (JackyChiu) [reply cluster/rpc_test.go]: Yep, the rest of the tests use the test config which uses 3 max connections
